### ISSUE TITLE
ALSA Problems

### ISSUE THREAD

**Issue by pine3825** [respeaker/mic_array#11]
Thanks for your supports.
I have another problems.
I can get the angle from Mic  Array by running "python kws_doa.py" 
But, three is ALSA problems.
Could you recommend how to fix?
========================================================================
jaehoon@jaehoon-UP:~/Workspace/ReSpeaker/mic_array$ ls /usr/bin | grep alsa
alsabat
alsaloop
alsamixer
alsamixergui
alsatplg
alsaucm

jaehoon@jaehoon-UP:~/Workspace/ReSpeaker/mic_array$ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 1: Array [ReSpeaker Microphone Array], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

jaehoon@jaehoon-UP:~/Workspace/ReSpeaker/mic_array$ python kws_doa.py 
ALSA lib confmisc.c:768:(parse_card) cannot find card '0'
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
...............
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
(0, 'ReSpeaker Microphone Array: USB Audio (hw:1,0)', 8L, 2L)
Use ReSpeaker Microphone Array: USB Audio (hw:1,0)

120
60

**Comment by xiongyihui** [comment]
It seems not a problem. Are you trying to avoid the following output message?

```
ALSA lib confmisc.c:768:(parse_card) cannot find card '0'
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
...............
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
```

**Comment by KillingJacky** [comment]
Will close this issue, please open a new issue if you have further questions.
