### ISSUE TITLE
Can I read the angle from Mic Array in Qt on linux? 

### ISSUE THREAD

**Issue by pine3825** [respeaker/mic_array#12]
Can I read the angle from Mic Array in Qt on linux?
Do you have any idea?

**Comment by Pillar1989** [comment]
Sorry, I have no idea about this issue. Maybe you can ask help with Qt forum？

**Comment by pine3825** [comment]
Dear
From below git, I tried that procedure. But not work.
So, I want to converter the python codes of kws_doa.py to C or C++ code.
Could you help me?
----------------------
https://github.com/bwhitman/respeaker-xmos-hid

**Comment by Pillar1989** [comment]
I think python is the best.

**Comment by KillingJacky** [comment]
Will close this issue, please open a new issue if you have further questions.
