### ISSUE TITLE
How can  I change the LED display?

### ISSUE THREAD

**Issue by pine3825** [respeaker/mic_array#13]
After VAD, I can display the LED with KWS_DOA.py.

How can I change the LED display like the original ReSpeak Core + MIC Array (Green + Blue  + Geen)

Thanks

**Comment by KillingJacky** [comment]
Modify `pixel_ring.py` in this repo. 
```python
        colors = [0] * 4 * self.PIXELS_N
        colors[0] = 0x4
        colors[1] = 0x40
        colors[2] = 0x4

        colors[4 + 1] = 0x8
        colors[4 * 11 + 1] = 0x8

        self.direction_template = colors
```
To help you understand the HID protocol, please refer to https://github.com/Fuhua-Chen/ReSpeaker-Microphone-Array-HID-tool/blob/master/respeaker%20micarray%20hid%20protocol.xlsx

**Comment by KillingJacky** [comment]
Will close this issue, please open a new issue if you have further questions.

**Comment by alias13e** [comment]
Are there codes for specific color values? Say instead of blue, green, and red I wanted to make the colors indigo, violet, and green, respectively. Does it use decimal, or hex, or something else?
