### ISSUE TITLE
Exception: can not find input device with 8 channel(s)

### ISSUE THREAD

**Issue by cogmeta** [respeaker/mic_array#14]
I get this error when trying to run python vad_doa.py  and python mic_array.py. LED tests are fine. Do i install a driver for it?

0, 'bcm2835 ALSA: - (hw:0,0)', 0L, 2L)
(1, 'bcm2835 ALSA: IEC958/HDMI (hw:0,1)', 0L, 2L)
(2, 'seeed-4mic-voicecard: - (hw:1,0)', 2L, 0L)
(3, 'sysdefault', 0L, 128L)
(4, 'playback', 0L, 128L)
(5, 'dmixed', 0L, 2L)
(6, 'ac108', 4L, 0L)
(7, 'dmix', 0L, 2L)
(8, 'default', 4L, 128L)
Traceback (most recent call last):
  File "vad_doa.py", line 52, in <module>
    main()
  File "vad_doa.py", line 23, in main
    with MicArray(RATE, CHANNELS, RATE * VAD_FRAMES / 1000)  as mic:
  File "/home/pi/respeaker/mic_array/mic_array.py", line 42, in __init__
    raise Exception('can not find input device with {} channel(s)'.format(self.channels))
Exception: can not find input device with 8 channel(s)

**Comment by cogmeta** [comment]
I can not see the device even after firmware update.

arecord -l
**** List of CAPTURE Hardware Devices ****
card 1: seeed4micvoicec [seeed-4mic-voicecard], device 0: bcm2835-i2s-ac108-codec0 ac108-codec0-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0

**Comment by cogmeta** [comment]
Do i need remove seeed-4mic-voicecard?

**Comment by cogmeta** [comment]
this is log of installing ..
VID = 0x2886, PID = 0x7, BCDDevice: 0x82
XMOS DFU application started - Interface 3 claimed
Detaching device from application mode.
Waiting for device to restart and enter DFU mode...
VID = 0x2886, PID = 0x7, BCDDevice: 0x82
... DFU firmware upgrade device opened
... Downloading image (respeaker_mic_array_8ch_raw.bin) to device
... Download complete
... Returning device to application mode

**Comment by xiongyihui** [comment]
The mic_array.py sports both 8 channels USB mic array and 4 channels Pi hat mic array.

You have the 4 mic array, change  [mic_array.py](https://github.com/respeaker/mic_array/blob/master/mic_array.py#L189) to

```
if __name__ == '__main__':
    test_4mic()
    # test_8mic()
```

To use [vad_doa.py](https://github.com/respeaker/mic_array/blob/master/vad_doa.py#L10), change `CHANNELS = 8` to

```
CHANNELS = 4
```
