### ISSUE TITLE
ReSpeaker Core or RaspberryPi ?

### ISSUE THREAD

**Issue by j4ques** [respeaker/mic_array#16]
Hello,

I'm planning to purchase the ReSpeaker Mic Array.
But I'm not sure which base to connect it with. 
For me it's a decision between the ReSpeaker Core and the Raspberry Pi 3. 
I'd like to create an Alexa like service that runs mainly offline. 
Some of my spoken queries should be sent to Google Assistant API for processing. 
I prefer developing in Python, and I aim to achieve the quickest response time (time from speaking command until answer)
Are there any suggestions on which might be "better" in terms of more flexible (or less painful to config)?

Thanks a lot

**Comment by xiongyihui** [comment]
I suggest to use raspberry pi with the Mic Array. The development is easier.

**Comment by j4ques** [comment]
Hello,

thanks lot! It's settled then. Raspberry it is. I'm curious though, would the same software run faster on the Respeaker core, or on the raspberry? Just to know whether I could tweak performance that way at a later time.

Thanks!!
