### ISSUE TITLE
ALSA lib pcm.c:8306:(snd_pcm_recover) overrun occurred

### ISSUE THREAD

**Issue by andrenatal** [respeaker/mic_array#17]
kws_doa.py is crashing after few seconds raising this error on raspbian stretch using the respeaker 4 mic hat for raspberry pi

**Comment by andrenatal** [comment]
Increasing [VAD_FRAMES](https://github.com/respeaker/mic_array/blob/master/vad_doa.py#L11) to 100 solved the problem without loosing accuracy neither performance.

**Comment by andrenatal** [comment]
it's still happening. it is only taking longer

**Comment by andrenatal** [comment]
Situation is little better when running with pulseaudio

**Comment by AlbertZhang411** [comment]
Hello sir, have you solved this problem?
