### ISSUE TITLE
Pixel-ring not working on Raspberry Pi Hat

### ISSUE THREAD

**Issue by andrenatal** [respeaker/mic_array#18]

**Comment by andrenatal** [comment]
[This](https://github.com/respeaker/mic_array/blob/master/kws_doa.py#L34) is not lighting the leds of my respeaker on Respeaker Pi Hat

**Comment by xiongyihui** [comment]
For the 4 mic array for raspberry pi, remove `pixel_ring.py` and run `pip install pixel_ring`
The [pixel_ring.py](https://github.com/respeaker/mic_array/blob/master/pixel_ring.py) is for the USB 6+1 Mic Array.
The document should be updated

**Comment by andrenatal** [comment]
Thank @xiongyihui , but it's still not working:
```

pi@raspberrypi:~/respeaker/mic_array $ python kws_doa.py
Traceback (most recent call last):
  File "kws_doa.py", line 5, in <module>
    from pixel_ring import pixel_ring
  File "/usr/local/lib/python2.7/dist-packages/pixel_ring/__init__.py", line 68, in <module>
    pixel_ring = PixelRing()
  File "/usr/local/lib/python2.7/dist-packages/pixel_ring/__init__.py", line 20, in __init__
    self.dev = APA102(num_led=self.PIXELS_N)
  File "/usr/local/lib/python2.7/dist-packages/pixel_ring/apa102.py", line 90, in __init__
    self.spi.open(bus, device)  # Open SPI port 0, slave device (CS) 1
IOError: [Errno 2] No such file or directory
```

**Comment by xiongyihui** [comment]
Did you enable the SPI interface on your Raspberry Pi? The LEDs use the SPI interface.

There is also a GPIO pin to control the LEDs. Have a look at [respeaker_4mic_array.py#L12](https://github.com/respeaker/pixel_ring/blob/master/examples/respeaker_4mic_array.py#L12)

**Comment by andrenatal** [comment]
@xiongyihui After enabling SPI, the error is gone, but the LEDs still do not light up :(

**Comment by andrenatal** [comment]
Oh, good news. None of the scripts here worked, but this https://github.com/respeaker/pixel_ring/blob/master/examples/respeaker_4mic_array.py  worked. I'm interested on ` pixel_ring.set_direction(direction)` but that doesn't seem to be working.

**Comment by andrenatal** [comment]
`Traceback (most recent call last):
  File "respeaker_4mic_array.py", line 28, in <module>
    pixel_ring.set_direction(300)
AttributeError: 'PixelRing' object has no attribute 'set_direction'`

**Comment by andrenatal** [comment]
`pixel_ring.wakeup(280)` seems to do the trick. Thanks @xiongyihui !
