### ISSUE TITLE
Set a fixed listening position

### ISSUE THREAD

**Issue by burnzzz** [respeaker/mic_array#23]
I am researching if it is possible to use the 7 mems mic array in a fixed installation and set it to a fixed listening direction. I see the get_direction() method, but would it be possible to focus the mic array beam to a fixed position? 

In my scenario I know where the speaker is and I want to suppress as much background noise as possible. Would be happy t get a hint in the right direction.

**Comment by xiongyihui** [comment]
You should have a try of  [the ODAS project](https://github.com/introlab/odas)
