### ISSUE TITLE
Noise Canceling and Acoustic Echo Cancellation

### ISSUE THREAD

**Issue by uchagani** [respeaker/mic_array#25]
Does noise cancelling and Acoustic Echo Cancellation only work if I connect my speaker to the ReSpeaker 7 Mic Array?  Or will it work even if i have my speaker connected to external source?

**Comment by xiongyihui** [comment]
Not recommend to use the AEC of the ReSpeaker 7 Mic Array~

**Comment by pkalebu** [comment]
@xiongyihui why isn't it recommended?

**Comment by xiongyihui** [comment]
@pkalebu The AEC of the USB Mic Arrray v1 is not good enough to use.

**Comment by pkalebu** [comment]
I see. Out of curiosity, how was this evaluated? What metrics did you look at?
