### ISSUE TITLE
No USB device found

### ISSUE THREAD

**Issue by sipvoip** [respeaker/mic_array#3]
pixel_ring.py is not finding my mic array even tho it is connected and shows up with the correct ID. 

[root@raspberry ~]# python pixel_ring.py
No USB device found

[root@raspberry ~]# lsusb
Bus 001 Device 004: ID 04d9:1702 Holtek Semiconductor, Inc. Keyboard LKS02
Bus 001 Device 005: ID 2886:0007  
Bus 001 Device 003: ID 0424:ec00 Standard Microsystems Corp. SMSC9512/9514 Fast Ethernet Adapter
Bus 001 Device 002: ID 0424:9514 Standard Microsystems Corp. SMC9514 Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

# dmesg output
[  261.084005] usb 1-1.2: new full-speed USB device number 5 using dwc2
[  261.173526] usb 1-1.2: not running at top speed; connect to a high speed hub
[  261.175199] usb 1-1.2: config 1 interface 4 altsetting 0 has 2 endpoint descriptors, different from the interface descriptor's value: 1
[  261.176926] usb 1-1.2: config 1 interface 4 altsetting 0 has 2 endpoint descriptors, different from the interface descriptor's value: 1
[  261.178785] usb 1-1.2: New USB device found, idVendor=2886, idProduct=0007
[  261.179153] usb 1-1.2: New USB device strings: Mfr=1, Product=3, SerialNumber=0
[  261.179474] usb 1-1.2: Product: ReSpeaker MicArray UAC2.0
[  261.179716] usb 1-1.2: Manufacturer: SeeedStudio
[  261.189399] hid-generic 0003:2886:0007.0003: hidraw2: USB HID v1.10 Device [SeeedStudio ReSpeaker MicArray UAC2.0] on usb-3f980000.usb-1.2/input4
[  263.534816] usbcore: registered new interface driver snd-usb-audio

**Comment by Mn0491** [comment]
hello, have you solved this issue? looking for a solution @sipvoip

**Comment by sipvoip** [comment]
Needed to switch the firmware.

**Comment by jhoelzl** [comment]
@sipvoip which firmware did you use to get it work?
