### ISSUE TITLE
ImportError: cannot import name SnowboyDetect

### ISSUE THREAD

**Issue by jacksun101** [respeaker/mic_array#5]
pi@raspberrypi:~/mic_array $ python kws_doa.py
Traceback (most recent call last):
  File "kws_doa.py", line 7, in <module>
    from snowboydetect import SnowboyDetect
ImportError: cannot import name SnowboyDetect

I've followed the instructions, any idea?

**Comment by xiongyihui** [comment]
Oh, one step is missing. Snowboy need be compiled.  Just added it.

We need run `make` in `snowboy/swig/Python`.

**Comment by pine3825** [comment]
In my case, there are same errors.

jaehoon@jaehoon-UP:~/Workspace/ReSpeaker/mic_array/snowboy/swig/Python$ make
make: Nothing to be done for 'all'.

Do you configure out this error?

**Comment by fjfo** [comment]
me too,

~/mic_array/snowboy/swig/Python $ make
make: Nothing to be done for 'all'

**Comment by fjfo** [comment]
do $make clean
and then
$make

After make it all, you can some how need to re soft link:

$ln -s snowboy/swig/Python3/snowboydetect.py snowboydetect.py
$ln -s snowboy/swig/Python3/_snowboydetect.so _snowboydetect.so

Now we can Import
