### ISSUE TITLE
xvsm firmware not recording using arecord -f S16_LE -r 16000 .

### ISSUE THREAD

**Issue by rahulrverma** [respeaker/mic_array#6]
xvsm firmware not recording using arecord -f S16_LE -r 16000.

The raw firmware records it. I am trying to use the array with Alexa AVS Sample app and want to use the xvsm firmware as the LEDs do not work with the raw firmware. The sample app does not work at all with the xvsm firmware. I am guessing it is not detecting any sound being recorded from the mic.

**Comment by xiongyihui** [comment]
How about:
```
arecord -v -f S16_LE -r 16000 -D plughw:1
```
If you disabled the on-board codec, the mic array cloud be 'plughw:0'.

When using `plughw` instead of `hw`, it will enable software mix to convert sample rate, format and channels.
