### ISSUE TITLE
KWS_DOA Error

### ISSUE THREAD

**Issue by pine3825** [respeaker/mic_array#9]
I run the below.
But there is import Error.
---------------------------------------------
python kws_doa.py 
Traceback (most recent call last):
  File "kws_doa.py", line 7, in <module>
    from snowboydetect import SnowboyDetect
ImportError: No module named snowboydetect
----------------------------------------------------------------------
So, I install as your instruction.
As below log, there is a version error.
Could you recommend for this problem??
=======================================
jaehoon@jaehoon-UP:~/Workspace/ReSpeaker/mic_array/snowboy/swig/Python$ sudo apt-get install python-dev libatlas-base-dev swig 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-dev is already the newest version (2.7.11-1).
libatlas-base-dev is already the newest version (3.10.2-9).
swig is already the newest version (3.0.8-0ubuntu3).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
jaehoon@jaehoon-UP:~/Workspace/ReSpeaker/mic_array/snowboy/swig/Python$ make
You need at least Swig 3.0.10 to run
Your current version is SWIG Version 3.0.8
/bin/sh: 1: exit: Illegal number: -1
Makefile:13: recipe for target 'checkversion' failed
make: *** [checkversion] Error 2

**Comment by xiongyihui** [comment]
You should install [latest swig](http://www.swig.org/download.html) or remove the version checking code of the Makefile

**Comment by pine3825** [comment]
Dear
 
I follow the recommended procedure.
But there is another error.
Do you have any comments?
 
I run another instruction.
--------------
jaehoon@jaehoon-UP:~/Workspace/ReSpeaker/mic_array/snowboy/swig/Python$ make
make: Nothing to be done for 'all'. 
------------------------------------------
jaehoon@jaehoon-UP:~/Workspace/ReSpeaker/mic_array$ python kws_doa.py 
Traceback (most recent call last):
  File "kws_doa.py", line 7, in &lt;module&gt;
    from snowboydetect import SnowboyDetect
ImportError: No module named snowboydetect 
 
 
-----Original Message-----

**Comment by xiongyihui** [comment]
Did you run these commands?
```
git submodule init
git submodule update
cd snowboy/swig/Python
sudo apt-get install python-dev libatlas-base-dev swig           # requiremetns to compile snowboy
make                                                 # if got an error of swig3.x.x, edit the Makefile and disable the swig version check.
echo 'from snowboydetect import *' > __init__.py     # create __init__.py for a python module
cd ../../..                                          # chang to the root directory of the repository
ln -s snowboy/swig/Python snowboydetect
python kws_doa.py
```

Make sure `__init__.py` is in `snowboy/swig/Python` and there is a soft link `snowboydetect` which links to `snowboy/swig/Python`

**Comment by pine3825** [comment]
Dear
 
I run the recommended commands
But there are several errors.
--------------------------------------
jaehoon@jaehoon-UP:~/Workspace/ReSpeaker/mic_array/snowboy/swig/Python$ sudo apt-get install python-dev libatlas-base-dev swig 
E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
 
--------------------------------------
jaehoon@jaehoon-UP:~/Workspace/ReSpeaker/mic_array$ python kws_doa.py
ALSA lib confmisc.c:768:(parse_card) cannot find card '0'
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1251:(snd_func_refer) error evaluating name
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
.... 
.... 
ALSA lib confmisc.c:1251:(snd_func_refer) error evaluating name
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4771:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM dmix
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
(0, 'ReSpeaker Microphone Array: USB Audio (hw:1,0)', 8L, 2L)
Use ReSpeaker Microphone Array: USB Audio (hw:1,0) 
 
-----Original Message-----

**Comment by pine3825** [comment]
Thanks for your advices.

I got the direction angle by wake-up word "alexa".
Can I change the wake-up word?
---------------------------------------------------------------
Use ReSpeaker Microphone Array: USB Audio (hw:1,0)

139

79

139

180
